// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// tw_start_watcher
void tw_start_watcher(std::string id, std::string path, bool recursive, std::vector<std::string> events, int debounce, Rcpp::Function callback, Rcpp::Nullable<std::string> pattern);
RcppExport SEXP _orchrd_tw_start_watcher(SEXP idSEXP, SEXP pathSEXP, SEXP recursiveSEXP, SEXP eventsSEXP, SEXP debounceSEXP, SEXP callbackSEXP, SEXP patternSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type id(idSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< bool >::type recursive(recursiveSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type events(eventsSEXP);
    Rcpp::traits::input_parameter< int >::type debounce(debounceSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type callback(callbackSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::string> >::type pattern(patternSEXP);
    tw_start_watcher(id, path, recursive, events, debounce, callback, pattern);
    return R_NilValue;
END_RCPP
}
// tw_stop_watcher
void tw_stop_watcher(std::string id);
RcppExport SEXP _orchrd_tw_stop_watcher(SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type id(idSEXP);
    tw_stop_watcher(id);
    return R_NilValue;
END_RCPP
}
// tw_pause_watcher
void tw_pause_watcher(std::string id);
RcppExport SEXP _orchrd_tw_pause_watcher(SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type id(idSEXP);
    tw_pause_watcher(id);
    return R_NilValue;
END_RCPP
}
// tw_resume_watcher
void tw_resume_watcher(std::string id);
RcppExport SEXP _orchrd_tw_resume_watcher(SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type id(idSEXP);
    tw_resume_watcher(id);
    return R_NilValue;
END_RCPP
}
// tw_update_callback
void tw_update_callback(std::string id, Rcpp::Function callback);
RcppExport SEXP _orchrd_tw_update_callback(SEXP idSEXP, SEXP callbackSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type id(idSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type callback(callbackSEXP);
    tw_update_callback(id, callback);
    return R_NilValue;
END_RCPP
}
// tw_active_ids
std::vector<std::string> tw_active_ids();
RcppExport SEXP _orchrd_tw_active_ids() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(tw_active_ids());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_orchrd_tw_start_watcher", (DL_FUNC) &_orchrd_tw_start_watcher, 7},
    {"_orchrd_tw_stop_watcher", (DL_FUNC) &_orchrd_tw_stop_watcher, 1},
    {"_orchrd_tw_pause_watcher", (DL_FUNC) &_orchrd_tw_pause_watcher, 1},
    {"_orchrd_tw_resume_watcher", (DL_FUNC) &_orchrd_tw_resume_watcher, 1},
    {"_orchrd_tw_update_callback", (DL_FUNC) &_orchrd_tw_update_callback, 2},
    {"_orchrd_tw_active_ids", (DL_FUNC) &_orchrd_tw_active_ids, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_orchrd(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
