# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.tw_start_watcher <- function(id, path, recursive, events, debounce, callback, pattern) {
    invisible(.Call('_orchrd_tw_start_watcher', PACKAGE = 'orchrd', id, path, recursive, events, debounce, callback, pattern))
}

.tw_stop_watcher <- function(id) {
    invisible(.Call('_orchrd_tw_stop_watcher', PACKAGE = 'orchrd', id))
}

.tw_pause_watcher <- function(id) {
    invisible(.Call('_orchrd_tw_pause_watcher', PACKAGE = 'orchrd', id))
}

.tw_resume_watcher <- function(id) {
    invisible(.Call('_orchrd_tw_resume_watcher', PACKAGE = 'orchrd', id))
}

.tw_update_callback <- function(id, callback) {
    invisible(.Call('_orchrd_tw_update_callback', PACKAGE = 'orchrd', id, callback))
}

.tw_active_ids <- function() {
    .Call('_orchrd_tw_active_ids', PACKAGE = 'orchrd')
}

